// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA4pMPSsGvgH2gz1V8I4QIhPG5wz4XpNQ',
    appId: '1:1092709638632:web:e38dac28aa3a9ab844845d',
    messagingSenderId: '1092709638632',
    projectId: 'rantel-5008c',
    authDomain: 'rantel-5008c.firebaseapp.com',
    storageBucket: 'rantel-5008c.firebasestorage.app',
    measurementId: 'G-WWQ7B9ZMP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw8wwm_eXVVCaBAk0RW3kJWECKIjtNkyo',
    appId: '1:1092709638632:android:878231ddde01a1b944845d',
    messagingSenderId: '1092709638632',
    projectId: 'rantel-5008c',
    storageBucket: 'rantel-5008c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dqGJ2iizaIpL99naRGr674Ulu763hus',
    appId: '1:1092709638632:ios:698d2e6ede231cb344845d',
    messagingSenderId: '1092709638632',
    projectId: 'rantel-5008c',
    storageBucket: 'rantel-5008c.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2dqGJ2iizaIpL99naRGr674Ulu763hus',
    appId: '1:1092709638632:ios:698d2e6ede231cb344845d',
    messagingSenderId: '1092709638632',
    projectId: 'rantel-5008c',
    storageBucket: 'rantel-5008c.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA4pMPSsGvgH2gz1V8I4QIhPG5wz4XpNQ',
    appId: '1:1092709638632:web:b0e4677a9be430e944845d',
    messagingSenderId: '1092709638632',
    projectId: 'rantel-5008c',
    authDomain: 'rantel-5008c.firebaseapp.com',
    storageBucket: 'rantel-5008c.firebasestorage.app',
    measurementId: 'G-TYS44CWRQF',
  );

}